FROM pi-agent:latest

RUN apt update && \
    apt install -y build-essential cron

RUN curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3 - --break-system-packages && \
    python3 -m pip install -U pip --break-system-packages

# python packages automonisaur
COPY install /install
# https://raw.githubusercontent.com/TheShellLand/automonisaur/refs/heads/master/requirements.txt 
#RUN python3 -m pip install -U -r /install/requirements.txt

# ansible
RUN git clone https://github.com/TheShellLand/antsable /antsable && \
    cd /antsable && \
    bash install-ansible.sh && \
    # chrome, docker
    bash ansible-local.sh playbooks/readyup-agents.yml

